name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test (${{ matrix.os }}, Node ${{ matrix.node-version }})
    strategy:
      fail-fast: false # Don't cancel other jobs if one fails
      matrix:
        # Note: Temporarily commented out due to timeout issues on free-tier runners with limited resources
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
        node-version: [18.x]
        include:
          - os: ubuntu-latest
            playwright-deps: chromium-browser
            xvfb: true
        #   - os: windows-latest
        #     playwright-deps: ""
        #     xvfb: false
        #   - os: macos-latest
        #     playwright-deps: chromium
        #     xvfb: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1 
      TEST_WORKSPACE: ${{ github.workspace }}/test-workspace

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # cache: "pnpm"

      # Install OS-specific dependencies
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.playwright-deps }} xvfb libxkbfile-dev libsecret-1-0

      - name: Install macOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install --cask chromium

      # Create test workspace
      - name: Create test directories
        run: |
          mkdir -p test-workspace
          chmod 777 test-workspace
        shell: bash

      # Main build and test steps
      - name: Install dependencies
        run: |
          pnpm install
        shell: bash

      # Run tests with OS-specific configuration
      - name: Run tests (Linux with Xvfb)
        if: matrix.xvfb
        run: xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' pnpm test
        env:
          DISPLAY: :99.0
          TEST_WORKSPACE: ${{ github.workspace }}/test-workspace

      - name: Run tests (Windows/macOS)
        if: ${{ !matrix.xvfb }}
        run: pnpm test

      - name: Build extension
        run: pnpm package

      # Artifact upload
    #   - name: Upload test results
    #     if: always()
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: test-results-${{ matrix.os }}-node-${{ matrix.node-version }}
    #       path: test-results
    #       retention-days: 7

    #   - name: Upload VSIX package
    #     if: success() && matrix.os == 'ubuntu-latest' # Only upload from Linux build
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: extension-package
    #       path: "*.vsix"
    #       retention-days: 7

    #   # Upload lockfile if it was generated
    #   - name: Upload generated lockfile
    #     if: success() && !hashFiles('**/pnpm-lock.yaml')
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: pnpm-lock
    #       path: pnpm-lock.yaml
    #       retention-days: 1
