name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

    #   - name: Install Puppeteer dependencies
    #     run: |
    #       sudo apt-get update
    #       sudo apt-get install -y chromium-browser

      - name: Run linter
        run: pnpm lint

      - name: Run type check
        run: pnpm check-types

    #   - name: Setup virtual display
    #     run: |
    #       sudo apt-get install -y xvfb
        #   Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & echo "Starting Xvfb..."
        shell: bash

      - name: Run tests
        # run: xvfb-run -a pnpm test
        run: pnpm test
        env:
          DISPLAY: :99.0

      - name: Build extension
        run: pnpm package

      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-${{ matrix.node-version }}
          path: |
            *.vsix
          retention-days: 7

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.node-version }}
          path: test-results
          retention-days: 7
